<a href="https://colab.research.google.com/github/MercylineOtwori/Everyday-git/blob/master/Mercyline_Otwori_SC212_0581_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print ("Hello world!")
print("I love my personal peace!")

Hello world!
I love my personal peace!


In [ ]:
print("I love coding")

I love coding


I am a Software Engineering student at Murang'a University of Technology.**bold text**

In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt


In [ ]:
print(tf.__version__)

2.19.0


In [ ]:
!pip install scikit-learn seaborn


In [ ]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target

df.head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [5]:
from sklearn.datasets import fetch_california_housing
import pandas as pd

housing = fetch_california_housing(as_frame=True)
df = housing.frame

df.head()


MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  MedHouseVal  
0    -122.23        4.526  
1    -122.22        3.585  
2    -122.24        3.521  
3    -122.25        3.413  
4    -122.25        3.422

In [7]:
from sklearn.datasets import load_iris, fetch_california_housing

# Iris
iris = load_iris()
X = iris.data
y = iris.target

# California Housing
housing = fetch_california_housing()
Xh = housing.data
yh = housing.target


In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
Xh_train, Xh_test, yh_train, yh_test = train_test_split(Xh, yh, test_size=0.2, random_state=42)


In [14]:
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    print(f"\n=== {name} ===")
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Precision:", precision_score(y_test, y_pred, average='weighted'))
    print("Recall:", recall_score(y_test, y_pred, average='weighted'))
    print("F1:", f1_score(y_test, y_pred, average='weighted'))



=== KNN ===
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1: 1.0

=== Naive Bayes ===
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1: 1.0

=== SVM ===
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1: 1.0

=== Decision Tree ===
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1: 1.0

=== Random Forest ===
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1: 1.0


In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

lr = LinearRegression()
lr.fit(Xh_train, yh_train)
y_pred = lr.predict(Xh_test)

print("Linear Regression")
print("MAE:", mean_absolute_error(yh_test, y_pred))
print("MSE:", mean_squared_error(yh_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(yh_test, y_pred)))
print("R2:", r2_score(yh_test, y_pred))


Linear Regression
MAE: 0.533200130495698
MSE: 0.5558915986952422
RMSE: 0.7455813830127749
R2: 0.5757877060324524


Linear Reggression


In [18]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=2)
X_poly_train = poly.fit_transform(Xh_train)
X_poly_test = poly.transform(Xh_test)

lr_poly = LinearRegression()
lr_poly.fit(X_poly_train, yh_train)
y_pred_poly = lr_poly.predict(X_poly_test)

print("Polynomial Regression R2:", r2_score(yh_test, y_pred_poly))


Polynomial Regression R2: 0.6456819711504156


Polynomial reggression


3)Ridge and Lasso


In [19]:
from sklearn.linear_model import Ridge, Lasso

ridge = Ridge(alpha=1.0)
ridge.fit(Xh_train, yh_train)
ridge_pred = ridge.predict(Xh_test)

lasso = Lasso(alpha=0.1)
lasso.fit(Xh_train, yh_train)
lasso_pred = lasso.predict(Xh_test)

print("Ridge R2:", r2_score(yh_test, ridge_pred))
print("Lasso R2:", r2_score(yh_test, lasso_pred))


Ridge R2: 0.5758549611440138
Lasso R2: 0.5318167610318159
